### ISSUE TITLE
GIDCollection vs. Collection

### ISSUE THREAD

**Issue by babsey** [compneuronmbu/nest-simulator#15]
I open this issue to ask why is it called GIDCollection and not Collection?

In my opinion, we dont have other type of collection, just only one. Thus. it is redundant to name it with 'GID*'.

Just speaking my mind.

**Comment by jougs** [comment]
I think I came up with the term `GIDCollection` a long time ago and no one ever really questioned it after that. If we should rename this, I would rather try to use a semantic name like `NeuronGroup` or `Population` instead of `Collection`. Also just speaking my mind ;-)

**Comment by heplesser** [comment]
I think Jochen has a very good point here! `GIDCollection` is a very technical term and we should strive to be closer to the language of the domain we are modelling. I feel a slight preference for `NeuronGroup` since it seems slightly more neutral than `Population`. `Population` is fine when we create, e.g., the E-population of a model (or a layer in a model), but once we start slicing or adding, the term `Population`  does not fit as well any more.

**Comment by babsey** [comment]
Thank you for quick response. Lets brainstorming.

I agree @heplesser concerning. The term `Population` is mostly assigned with a function/purpose.

`NeuronGroup` is a good semantic term but we also have other element types such as `stimulator` and `recorder`. How do they fit in this? Why not having a generic term just like as `Group` or `Collection`?

**Comment by babsey** [comment]
I close this issue because it has been discussed.
